version: 2

models:
  - name: stg_transactions
    description: "Cleaned bronze file, one row per transaction, normalized and validated before loading into Silver/Gold marts."

    columns:
      - name: transaction_id
        description: "Unique identifier for the transaction."
        tests:
          - not_null
          - unique
          - unique_transaction_id  # Custom test

      - name: customer_id
        description: "Customer linked to the transaction."
        tests:
          - not_null

      - name: amount
        description: "Monetary amount of the transaction in the raw currency."
        tests:
          - not_null
          - non_negative
          - amount_not_outlier  # Custom test for extreme amounts

      - name: status
        description: "Normalized status flag from the source system."
        tests:
          - not_null
          - accepted_status     # Custom test enforcing strict values

      - name: transaction_ts
        description: "Event timestamp of the transaction."
        tests:
          - not_null
          - valid_timestamp
          - not_in_future       # Custom test

      - name: transaction_date
        description: "Date component derived from transaction_ts for partitioning/grouping."
        tests:
          - not_null

    tests:
      - no_duplicate_rows
